# Generated by Django 3.2.4 on 2024-07-27 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image_url', models.URLField()),
                ('name', models.CharField(max_length=64)),
                ('company_position', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='flan',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
