# Generated by Django 3.2.4 on 2024-07-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20240726_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='review',
            field=models.TextField(default='-'),
        ),
    ]
